### ISSUE TITLE
Extrae fails to build with `--without-papi` option since 4.2.6

### ISSUE THREAD

**Issue by valentin-seitz** [bsc-performance-tools/extrae#133]
When trying to build the current extrae master (e2258fb5ec75447a1646488cf5a3ac0e32b57321) or backwards until version 4.2.6 configured like: 
`/configure --without-mpi --without-unwind --without-papi --without-binutils --prefix=<someprefix>` 

I run into the following error: 
```
In file included from calltrace.c:30:
../../src/tracer/hwc/common_hwc.h:56:39: error: ‘PAPI_HUGE_STR_LEN’ undeclared here (not in a function)
   56 | #define MAX_HWC_DESCRIPTION_LENGTH  2*PAPI_HUGE_STR_LEN
```

Looking close into the offending line it becomes obvious that a simple `#ifdef` should do the trick of an undefined `PAPI_HUGE_STR_LEN` macro as the current implementation implicitly assumes its available through the PAPI headers. 

https://github.com/bsc-performance-tools/extrae/blob/e2258fb5ec75447a1646488cf5a3ac0e32b57321/src/tracer/hwc/common_hwc.h#L55-L57 

The commit that seems to introduce the breaking changes seems to be def5b58.

**Comment by valentin-seitz** [comment]
Seems to be solved by 435e136
